global:
  resolve_timeout: 1s

route:
  group_by: ['alertname']
  group_wait: 1s
  group_interval: 1s
  repeat_interval: 1s
  receiver: 'console'

receivers:
  - name: 'console'
    webhook_configs:
      - url: 'http://localhost:5001/'  # Pode apontar para qualquer endpoint de teste
