version: "3.9"

services:
  api:
    container_name: detect-alerts-api
    build: .
    command: flask run --host=0.0.0.0 --port=5000
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DB_USER=postgres
      - DB_PASS=postgres
      - DB_HOST=db
      - DB_NAME=alertsdb
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    depends_on:
      - db

  db:
    container_name: detect-alerts-postgres
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: alertsdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    container_name: detect-alerts-pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db

volumes:
  pgdata: